language: c

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      jdk: openjdk11

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y default-jdk-headless ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then if [[ ! -n $JAVA_HOME ]]; then export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk-13.0.1.jdk/Contents/Home" ; fi ; fi

install:
  - echo $JAVA_HOME
  - java --version

script:
  - make
